# Preproc for bags where TFs and other messages start being recorded only 60s after start and ICP is bad
out_format: '{bag_base}.preproc{ext}'
compression: lz4
filters:
  - MergeInitialStaticTf:
      add_tags: [ "copied_tf" ]
      delay: 65.0
  - CopyFirstTfToBagStart:
      add_tags: [ "copied_tf" ]
      max_delay: 65.0
  - RemovePasswordsFromParams: {}
  # Make sure we have TFs also for images that have stamps slightly before the start of the bag
  - FixHeader:
      include_tags: [ "copied_tf" ]
      stamp_offset: 58.0
      receive_stamp_from_header: true

  # Drop the start of the bag without most data
  - Drop:
      include_time_ranges: [[0, 61]]
      exclude_tags: [ "copied_tf" ]

  - Remap:
      "/points_filtered_kontron": "/points_filtered"
  - Copy:
      "/marv/cartesian_controller/cmd_vel": "/cmd_vel"
      "/marv/cartesian_controller/odom": "/odom_2d"
      "/marv/joint_states": "/joint_states"
  - Topics:
      exclude_topics:
        - /icp_diagnostics
        - /icp_odom
        - /robot_bounding_box_debug
        - /robot_bounding_sphere_debug
        - /robot_model_for_bounding_box
        - /robot_model_for_bounding_sphere
        - /rosout
        - /rosout_agg
  - Transforms:
      exclude_parents:
        - map
  - MagnetometerGaussToTesla:
      scale_covariance: False
      include_topics:
        - imu/mag
        - imu/mag_bias
        - imu/mag_unbiased
  - AddStaticTF:
      - frame_id: base_link
        child_frame_id: base_footprint
        transform: [0.0, 0.0, -0.125, 0.0, 0.0, 0.0]
  - RemoveInvalidTF: { }
  - DeduplicateTF: { }