out_format: '{bag_base}.blurred_faces{ext}'
compression: lz4
copy_params: False
filters:
  - TopicTypes:
      include_types:
        - sensor_msgs/CompressedImage
        - sensor_msgs/Image
        - vision_msgs/Detection2DArray
  - Topics:
      exclude_topics:
        - camera_front_thermo/image_raw
        - oak/stereo/image_raw/compressedDepth
        
  # husky_2025-02-07-15-10-53
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-10-53"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [[ 60, 70 ], [ 210, 217 ], [ 270, 275 ]]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-10-53"]
      include_topics: ["camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces"]
      exclude_time_ranges: [[28, 33], [68, 75], [155, 172], [180, 198], [212, 225]]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-10-53"]
      include_topics: ["camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces"]
      exclude_time_ranges: [[0, 55], [72, 100], [140, 160], [170, 185], [195, 217]]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-10-53"]
      include_topics: ["camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces"]
      exclude_time_ranges: [[35, 46], [55, 62], [76, 88]]

  # husky_2025-02-07-15-17-04
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-17-04"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-17-04"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-17-04"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 30 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-17-04"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 20, 50 ] ]

  # husky_2025-02-07-15-18-09
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-18-09"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 145, 155 ], [ 360, 380 ], [ 445, 455 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-18-09"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 13, 45 ], [ 80, 105 ], [ 195, 210 ], [ 225, 235 ], [ 295, 330 ], [ 370, 415 ], [ 445, 455 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-18-09"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 115 ], [ 130, 185 ], [ 215, 250 ], [ 310, 340 ], [ 375, 450 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-18-09"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 15 ], [ 27, 60 ], [ 140, 160 ], [ 175, 190 ], [ 220, 225 ], [ 320, 340 ], [ 410, 461 ] ]
  
  # husky_2025-02-07-15-27-03
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-27-03"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 30, 80 ], [ 100, 108 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-27-03"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 35, 80 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-27-03"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 10 ], [ 35, 80 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-15-27-03"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 35, 70 ], [ 100, 108 ] ]
  
  # husky_2025-02-07-16-06-49
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-06-49"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 50, 70 ], [ 90, 136 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-06-49"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 5, 40 ], [ 55, 70 ], [ 80, 100 ], [ 125, 136 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-06-49"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 55 ], [ 65, 90 ], [ 100, 136 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-06-49"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 35, 60 ], [ 95, 130 ] ]
  
  # husky_2025-02-07-16-16-56
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-16-56"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 70, 75 ], [ 85, 90 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-16-56"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 65, 90 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-16-56"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 30 ], [ 40, 80 ], [ 90, 115 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-16-56"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ ]
  
  # husky_2025-02-07-16-20-58
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-20-58"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-20-58"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-20-58"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 25 ], [ 35, 50 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-20-58"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 40 ] ]

  # husky_2025-02-07-16-22-48
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-22-48"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 40, 95 ], [ 105, 115 ], [ 205, 225 ], [ 300, 310 ], [ 370, 385 ], [ 410, 425 ], [ 470, 490 ], [ 500, 510 ], [ 520, 540 ], [ 575, 600 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-22-48"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 70 ], [ 110, 125 ], [ 150, 165 ], [ 205, 250 ], [ 265, 310 ], [ 320, 340 ], [ 370, 285 ], [ 410, 425 ], [ 490, 540 ], [ 585, 600 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-22-48"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 15, 100 ], [ 120, 325 ], [ 335, 440 ], [ 485, 555 ], [ 590, 619 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-22-48"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 45, 70 ], [ 80, 95 ], [ 135, 145 ], [ 170, 180 ], [ 190, 205 ], [ 250, 260 ], [ 295, 325 ], [ 340, 360 ], [ 410, 425 ], [ 475, 490 ], [ 520, 545 ], [ 590, 600 ] ]
  
  # husky_2025-02-07-16-35-45
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-35-45"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 20, 35 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-35-45"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 20, 35 ], [ 55, 68 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-35-45"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 60 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-35-45"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 25 ], [ 40, 60 ] ]

  # husky_2025-02-07-16-46-52
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-46-52"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 0, 10 ], [ 110, 145 ], [ 205, 230 ], [ 250, 335 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-46-52"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 110, 210 ], [ 245, 275 ], [ 350, 380 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-46-52"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 45 ], [ 105, 115 ], [ 140, 210 ], [ 225, 245 ], [ 330, 468 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-46-52"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 5, 40 ], [ 95, 110 ], [ 125, 155 ], [ 215, 235 ], [ 290, 340 ] ]
  
  # husky_2025-02-07-16-55-40
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-55-40"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-55-40"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 65, 75 ], [ 220, 230 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-55-40"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 269 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-16-55-40"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ ]
  
  # husky_2025-02-07-17-18-26
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-17-18-26"]
      include_topics:
        - camera_front/image_color/compressed
        - camera_front_thermo/image8/compressed
        - camera_front_thermo/image8_norm/compressed
        - camera_front_thermo/image_heatmap/compressed
        - oak/left/image_raw/compressed
        - oak/right/image_raw/compressed
        - oak/rgb/image_raw/compressed
        - camera_front/image_color/anonymized_faces
        - camera_front_thermo/image8/anonymized_faces
        - camera_front_thermo/image8_norm/anonymized_faces
        - camera_front_thermo/image_heatmap/anonymized_faces
        - oak/left/image_raw/anonymized_faces
        - oak/right/image_raw/anonymized_faces
        - oak/rgb/image_raw/anonymized_faces
      exclude_time_ranges: [ [ 240, 266 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-17-18-26"]
      include_topics: [ "camera_left/image_color/compressed", "camera_left/image_color/anonymized_faces" ]
      exclude_time_ranges: [ ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-17-18-26"]
      include_topics: [ "camera_rear/image_color/compressed", "camera_rear/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 147 ] ]
  - Drop:
      include_tags: ["bag_base:husky_2025-02-07-17-18-26"]
      include_topics: [ "camera_right/image_color/compressed", "camera_right/image_color/anonymized_faces" ]
      exclude_time_ranges: [ [ 0, 35 ] ]
  
  - ExportMessageInfoToCSV:
      csv_file: "{bag_base}.faces.csv"
      use_header_stamp: True
      include_types: ["vision_msgs/Detection2DArray"]
