compression: lz4
copy_params: false
filters:
  - Topics:
      include_topics:
        - '/tf_static'
  - AddStaticTF:
      transforms:
      - frame_id: base_link
        child_frame_id: base_footprint
        transform: [0.0, 0.0, -0.125, 0.0, 0.0, 0.0]