# Fix Husky cmd_vel in already generated preproc files
out_format: '{dirname}/{basename}{ext}'
compression: lz4
copy_params: True
filters:
  - Copy:
      "husky_velocity_controller/cmd_vel": "cmd_vel"
      "husky_velocity_controller/odom": "odom_2d"