out_format: '{bag_base}.flippers{ext}'
compression: lz4
copy_params: False
filters:
  - Topics:
      include_topics:
        - /marv/flippers/joint_states
  - ExtractJointStatesVelocityAsCommands:
      joints:
        - front_left_flipper_j
        - front_right_flipper_j
        - rear_left_flipper_j
        - rear_right_flipper_j
      cmd_topic: /marv/flippers_velocity_controller/cmd_vel
      min_velocity: 0.02
      joint_states_topic: /marv/flippers/joint_states
  - Drop:
      exclude_tags: ["generated"]