out_format: '{bag_base}.postproc{ext}'
compression: lz4
filters:
  - AddSubtitles:
      subtitles_file: '{bag_base}.srt'
      topic: /commentary
  - StampTwist:
      source_topic: "/cmd_vel"
  - DeduplicateTF: {}
